FROM node:14-alpine

USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install

#Can be removed if we have mapped volume to the local src folder.
COPY --chown=node:node ./ ./

CMD ["npm","start"]